#!/bin/bash
dpkg-query -l virtualenv
if [ $? -eq 0 ];
then
  sudo apt-get install python-virtualenv;
fi
virtualenv flask
source flask/bin/activate
pip install flask
pip install flask-sqlalchemy
pip install sqlalchemy-migrate
pip install flask-wtf
pip install flipflop
deactivate
